/**
 * Jev-vs-engine chess loop.
 *
 * Requirements:
 *   - Node.js 20+
 *   - TYPESAFE_API_KEY set in the environment
 *   - npm install
 *
 * Run with:
 *   npm start
 *
 * Jev plays White and chooses from moves generated by js-chess-engine.
 */

import { choice, TypeSafeClient } from "@typesafe-ai/sdk";
import { stdout } from "node:process";

// Version 1 is pinned because it supports Node 20, but it does not ship types.
// @ts-expect-error js-chess-engine v1.0.3 has no TypeScript declaration file.
import jsChessEngine from "js-chess-engine";

type Color = "white" | "black";
type AILevel = 0 | 1 | 2 | 3 | 4;
type MovesMap = Record<string, string[]>;
type HistoryEntry = Record<string, string>;

type BoardConfig = {
  turn: Color;
  pieces: Record<string, string>;
  isFinished: boolean;
  check: boolean;
  checkMate: boolean;
};

type ChessGame = {
  move(from: string, to: string): HistoryEntry;
  moves(): MovesMap;
  aiMove(level?: AILevel): HistoryEntry;
  printToConsole(): void;
  exportJson(): BoardConfig;
  exportFEN(): string;
};

const { Game } = jsChessEngine as {
  Game: new () => ChessGame;
};

type ChessMove = {
  from: string;
  to: string;
};

type JevTurn = {
  fen: string;
  color: Color;
  pieces: Record<string, string>;
  legalMoves: ChessMove[];
};

type JevAnalysis = {
  model: string;
  priority: string;
  priorityConfidence: number;
  choice: string;
  choiceConfidence: number;
  candidates: Array<[move: string, probability: number]>;
};

type JevDecision = {
  move: ChessMove;
  analysis: JevAnalysis;
};

const JEV_COLOR: Color = "white";
const ENGINE_COLOR: Color = JEV_COLOR === "white" ? "black" : "white";
const ENGINE_LEVEL: AILevel = 3;
const MAX_PLIES = 300;
const ENGINE_LEVELS: Record<AILevel, { name: string; lookahead: string }> = {
  0: { name: "Well-trained monkey", lookahead: "1–2 plies" },
  1: { name: "Beginner", lookahead: "2–4 plies" },
  2: { name: "Intermediate", lookahead: "2–4 plies" },
  3: { name: "Advanced", lookahead: "3–5 plies" },
  4: { name: "Experienced", lookahead: "4–5 plies" },
};

function flattenMoves(moves: MovesMap): ChessMove[] {
  return Object.entries(moves).flatMap(([from, destinations]) =>
    destinations.map((to) => ({ from, to })),
  );
}

function formatMove(move: ChessMove): string {
  return `${move.from.toLowerCase()}${move.to.toLowerCase()}`;
}

function unpackEngineMove(move: HistoryEntry): ChessMove {
  const entry = Object.entries(move)[0];

  if (!entry) {
    throw new Error("The engine returned an empty move.");
  }

  return { from: entry[0], to: entry[1] };
}

function renderJevAnalysis(analysis: JevAnalysis): void {
  console.log("\nJev analysis");
  console.log(`Model: ${analysis.model}`);
  console.log(
    `Priority: ${analysis.priority} (${(analysis.priorityConfidence * 100).toFixed(1)}%)`,
  );
  console.log("Top moves:");

  for (const [move, probability] of analysis.candidates) {
    const barLength = Math.round(probability * 20);
    const bar = "#".repeat(barLength).padEnd(20, ".");
    console.log(`  ${move.padEnd(5)} [${bar}] ${(probability * 100).toFixed(1)}%`);
  }

  console.log(
    `Choice: ${analysis.choice} (${(analysis.choiceConfidence * 100).toFixed(1)}% confidence)`,
  );
}

function renderGame(
  game: ChessGame,
  state: BoardConfig,
  ply: number,
  moveLog: string[],
  latestJevAnalysis?: JevAnalysis,
): void {
  // Refresh one screen in an interactive terminal; retain normal logs elsewhere.
  if (stdout.isTTY) {
    stdout.write("\u001B[2J\u001B[H");
  }

  const activePlayer = state.turn === JEV_COLOR ? "Jev" : "Engine";
  const turnLabel = `${activePlayer} (${state.turn[0].toUpperCase()}${state.turn.slice(1)})`;

  console.log(
    `Jev: ${JEV_COLOR.toUpperCase()} (uppercase)  |  Engine: ${ENGINE_COLOR.toUpperCase()} (lowercase)`,
  );
  console.log(
    `Ratings: Jev UNRATED  |  Engine UNRATED — level ${ENGINE_LEVEL} ${ENGINE_LEVELS[ENGINE_LEVEL].name}, ${ENGINE_LEVELS[ENGINE_LEVEL].lookahead}`,
  );
  console.log("The library does not publish an Elo rating; results against rated opponents are needed to estimate one.");
  console.log(
    state.isFinished
      ? `Game over after ${ply} plies`
      : `Ply ${ply + 1} — ${turnLabel} to move${state.check ? " — CHECK" : ""}`,
  );

  if (moveLog.length > 0) {
    console.log(`Last move: ${moveLog.at(-1)}`);
  }

  console.log("");
  game.printToConsole();
  console.log(`Moves: ${moveLog.join(" ") || "(none yet)"}`);

  if (latestJevAnalysis) {
    renderJevAnalysis(latestJevAnalysis);
  }
}

/**
 * Ask Jev to select one of the engine-generated legal moves. Using each move
 * as a choice label makes an illegal move impossible in a valid API response.
 */
async function chooseJevMove(
  client: TypeSafeClient,
  turn: JevTurn,
): Promise<JevDecision> {
  if (turn.legalMoves.length === 0) {
    throw new Error("Jev has no legal moves, but the game is not marked as finished.");
  }

  if (turn.legalMoves.length === 1) {
    const forcedMove = turn.legalMoves[0];
    const label = formatMove(forcedMove);
    return {
      move: forcedMove,
      analysis: {
        model: "forced move",
        priority: "only legal move",
        priorityConfidence: 1,
        choice: label,
        choiceConfidence: 1,
        candidates: [[label, 1]],
      },
    };
  }

  const movesByLabel = Object.fromEntries(
    turn.legalMoves.map((move) => [formatMove(move), null]),
  );

  const response = await client.systemOne({
    state: {
      game: "chess",
      player: "Jev",
      color: turn.color,
      fen: turn.fen,
      pieces: turn.pieces,
    },
    questions: {
      move: choice(
        "Choose the strongest legal chess move. Choice labels use coordinate notation: the first square is the origin and the second is the destination.",
        movesByLabel,
      ),
      priority: choice("What is the most important strategic consideration in this position?", {
        king_safety: "Protect the king or exploit an exposed enemy king.",
        tactics: "Look for checks, captures, threats, and forcing combinations.",
        material: "Win material or avoid losing material.",
        development: "Develop pieces and improve coordination.",
        center_control: "Occupy or influence important central squares.",
        piece_activity: "Improve the scope and placement of active pieces.",
        pawn_structure: "Improve pawns or exploit structural weaknesses.",
      }),
    },
  });

  const selectedLabel = response.answers.move.choice;
  const selected = turn.legalMoves.find(
    (move) => formatMove(move) === selectedLabel,
  );

  if (!selected) {
    throw new Error(`Jev returned an unknown move: ${selectedLabel}`);
  }

  const priority = response.answers.priority.choice.replaceAll("_", " ");
  const candidates = Object.entries(response.answers.move.probabilities)
    .sort(([, first], [, second]) => second - first)
    .slice(0, 5);

  return {
    move: selected,
    analysis: {
      model: response.model,
      priority,
      priorityConfidence: response.answers.priority.confidence,
      choice: selectedLabel,
      choiceConfidence: response.answers.move.confidence,
      candidates,
    },
  };
}

function describeResult(state: BoardConfig): string {
  if (state.checkMate) {
    const winner = state.turn === "white" ? "Black" : "White";
    return `Checkmate. ${winner} wins.`;
  }

  return "Draw.";
}

async function playGame(): Promise<void> {
  const client = new TypeSafeClient();
  const game = new Game();
  const moveLog: string[] = [];
  let latestJevAnalysis: JevAnalysis | undefined;

  for (let ply = 0; ply < MAX_PLIES; ply += 1) {
    const state = game.exportJson();
    renderGame(game, state, ply, moveLog, latestJevAnalysis);

    if (state.isFinished) {
      console.log(`\n${describeResult(state)}`);
      return;
    }

    if (state.turn === JEV_COLOR) {
      console.log("Jev is thinking...");
      const decision = await chooseJevMove(
        client,
        {
          fen: game.exportFEN(),
          color: state.turn,
          pieces: state.pieces,
          legalMoves: flattenMoves(game.moves()),
        },
      );
      const move = decision.move;
      latestJevAnalysis = decision.analysis;

      game.move(move.from, move.to);
      moveLog.push(formatMove(move));
      console.log(`Jev played ${formatMove(move)}.`);
      continue;
    }

    console.log("Engine is thinking...");
    const move = unpackEngineMove(game.aiMove(ENGINE_LEVEL));
    moveLog.push(formatMove(move));
    console.log(`Engine played ${formatMove(move)}.`);
  }

  renderGame(game, game.exportJson(), MAX_PLIES, moveLog, latestJevAnalysis);
  console.log(`\nStopped after ${MAX_PLIES} plies to prevent an endless game.`);
  console.log(`Final FEN: ${game.exportFEN()}`);
  console.log(`Moves: ${moveLog.join(" ")}`);
}

await playGame();
